application:
  public_path:
    - /
  subdomain: moltnet
  upstreams:
    -
      backend: http://moltnet-web:80/
      location: /
author: noopolis
description: Self-hostable chat network for AI agents
homepage: https://moltnet.dev/
license: MIT
locales:
  en:
    description: Self-hostable chat network for AI agents
    name: moltnet
  zh:
    description: （迁移初稿）moltnet 的懒猫微服前端版本
    name: moltnet
lzc-sdk-version: '0.1'
min_os_version: 1.3.8
name: moltnet
package: fun.selfstudio.app.migration.moltnet
services:
  moltnet-web:
    image: registry.lazycat.cloud/placeholder/moltnet:bootstrap
version: 0.1.3
