import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import { spawn } from "node:child_process";

const APP_DIR = "/app";
const STATE_DIR = process.env.CRUCIX_STATE_DIR || "/crucix-state";
const CONFIG_DIR = process.env.CRUCIX_CONFIG_DIR || `${STATE_DIR}/config`;
const CONFIG_PATH = process.env.CRUCIX_CONFIG_PATH || `${CONFIG_DIR}/.env`;
const DOTENV_PATH = `${APP_DIR}/.env`;
const RUNTIME_MANIFEST_PATH = "/lzcapp/run/manifest.yml";
const PACKAGE_MANIFEST_PATH = "/lzcapp/pkg/manifest.yml";
const MANIFEST_ENV_NAMES = ["LLM_PROVIDER", "LLM_API_KEY", "LLM_MODEL", "OLLAMA_BASE_URL"];

async function exists(path) {
  try {
    await access(path, fsConstants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function envContent(values, comment) {
  return [
    comment,
    ...Object.entries(values).map(([key, value]) => `${key}=${String(value || "").replace(/\r?\n/g, " ").trim()}`),
    "",
  ].join("\n");
}

function parseEnvText(raw) {
  const result = {};
  for (const line of String(raw || "").split(/\r?\n/)) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;
    result[match[1]] = match[2] || "";
  }
  return result;
}

function parseManifestEnv(raw) {
  const result = {};
  for (const line of String(raw || "").split(/\r?\n/)) {
    const match = line.match(/^\s*-\s+([A-Za-z_][A-Za-z0-9_]*)=(.*)\s*$/);
    if (!match) continue;
    const key = match[1];
    if (!MANIFEST_ENV_NAMES.includes(key)) continue;
    result[key] = match[2] || "";
  }
  return result;
}

async function manifestEnv() {
  for (const path of [RUNTIME_MANIFEST_PATH, PACKAGE_MANIFEST_PATH]) {
    if (!(await exists(path))) continue;
    const raw = await readFile(path, "utf8").catch(() => "");
    const parsed = parseManifestEnv(raw);
    if (Object.keys(parsed).length > 0) return parsed;
  }
  return {};
}

async function runtimeEnv() {
  const manifestValues = await manifestEnv();
  return {
    LLM_PROVIDER: process.env.LLM_PROVIDER || manifestValues.LLM_PROVIDER || "",
    LLM_API_KEY: process.env.LLM_API_KEY || manifestValues.LLM_API_KEY || "",
    LLM_MODEL: process.env.LLM_MODEL || manifestValues.LLM_MODEL || "",
    OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL || manifestValues.OLLAMA_BASE_URL || "",
  };
}

async function syncConfigFiles() {
  await mkdir(CONFIG_DIR, { recursive: true });
  const content = envContent(await runtimeEnv(), "# Generated by LazyCat Crucix bootstrap.");
  await writeFile(CONFIG_PATH, content, "utf8");
  await writeFile(DOTENV_PATH, content, "utf8");
}

async function mergeExistingSecrets() {
  if (!(await exists(CONFIG_PATH))) return;
  const existing = parseEnvText(await readFile(CONFIG_PATH, "utf8").catch(() => ""));
  if (!process.env.LLM_API_KEY && existing.LLM_API_KEY) {
    process.env.LLM_API_KEY = existing.LLM_API_KEY;
  }
}

await mergeExistingSecrets();
await syncConfigFiles();

const child = spawn("node", ["server.mjs"], {
  cwd: APP_DIR,
  env: {
    ...process.env,
    PORT: process.env.PORT || "3117",
  },
  stdio: "inherit",
});

child.on("exit", (code, signal) => {
  if (signal) {
    process.exit(0);
  }
  process.exit(code ?? 0);
});
