import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import { spawn } from "node:child_process";

const APP_DIR = "/app";
const STATE_DIR = process.env.CRUCIX_STATE_DIR || "/crucix-state";
const CONFIG_DIR = process.env.CRUCIX_CONFIG_DIR || `${STATE_DIR}/config`;
const CONFIG_PATH = process.env.CRUCIX_CONFIG_PATH || `${CONFIG_DIR}/.env`;
const DOTENV_PATH = `${APP_DIR}/.env`;

async function exists(path) {
  try {
    await access(path, fsConstants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function envContent(values, comment) {
  return [
    comment,
    ...Object.entries(values).map(([key, value]) => `${key}=${String(value || "").replace(/\r?\n/g, " ").trim()}`),
    "",
  ].join("\n");
}

function runtimeEnv() {
  return {
    LLM_PROVIDER: process.env.LLM_PROVIDER || "",
    LLM_API_KEY: process.env.LLM_API_KEY || "",
    LLM_MODEL: process.env.LLM_MODEL || "",
    OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL || "",
  };
}

async function syncConfigFiles() {
  await mkdir(CONFIG_DIR, { recursive: true });
  const content = envContent(runtimeEnv(), "# Generated by LazyCat Crucix bootstrap.");
  await writeFile(CONFIG_PATH, content, "utf8");
  await writeFile(DOTENV_PATH, content, "utf8");
}

async function mergeExistingSecrets() {
  if (!(await exists(CONFIG_PATH))) return;
  const raw = await readFile(CONFIG_PATH, "utf8").catch(() => "");
  const existing = Object.fromEntries(
    String(raw)
      .split(/\r?\n/)
      .map((line) => line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/))
      .filter(Boolean)
      .map((match) => [match[1], match[2]]),
  );
  if (!process.env.LLM_API_KEY && existing.LLM_API_KEY) {
    process.env.LLM_API_KEY = existing.LLM_API_KEY;
  }
}

await mergeExistingSecrets();
await syncConfigFiles();

const child = spawn("node", ["server.mjs"], {
  cwd: APP_DIR,
  env: {
    ...process.env,
    PORT: process.env.PORT || "3117",
  },
  stdio: "inherit",
});

child.on("exit", (code, signal) => {
  if (signal) {
    process.exit(0);
  }
  process.exit(code ?? 0);
});
