lzc-sdk-version: '0.1'
package: fun.selfstudio.app.migration.fastclaw
version: 0.20.0
min_os_version: 1.3.8
name: fastclaw
description: Faster and better openclaw alternative
license: MIT
homepage: https://github.com/fastclaw-ai/fastclaw
author: fastclaw-ai
application:
  subdomain: fastclaw
  public_path:
    - /
  upstreams:
    -
      location: /
      backend: http://fastclaw:18953/
services:
  fastclaw:
    image: ghcr.io/codeeagle/fastclaw:ce71345a2091
data_paths:
  - host: /lzcapp/var/data/fastclaw
    container: /root/.fastclaw
    description: FastClaw config, agents, skills, memory
locales:
  en:
    name: fastclaw
    description: Faster and better openclaw alternative
  zh:
    name: fastclaw
    description: （迁移初稿）Fastclaw 的懒猫微服版本
