events {
    worker_connections 1024;
}
http {
    include mime.types;
    server {
        listen 80;
        root /usr/share/nginx/html;
        
        location = / {
            if ($request_method = GET) {
                rewrite ^ /index.html break;
            }
            proxy_pass http://gateway:8443;
        }
        
        location / {
            error_page 404 = @proxy;
            log_not_found off;
        }
        
        location @proxy {
            proxy_pass http://gateway:8443;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
