lzc-sdk-version: "0.1"
package: fun.selfstudio.app.migration.taoyuan
version: 2.2.0
min_os_version: 1.3.8
name: TaoYuan
description: (LazyCat Auto-build) Chinese pastoral life sim game running fully in the browser
license: CC-BY-NC-4.0
homepage: https://github.com/setube/taoyuan
author: setube
application:
  subdomain: taoyuan
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://taoyuan-web:80/
services:
  taoyuan-web:
    image: registry.lazycat.cloud/invokerlaw/codeeagle/taoyuan:2c527085760092f7
    environment: []
    binds: []
    setup_script: |
      if [ -f /lzcapp/pkg/content/index.html ]; then
        rm -rf /usr/share/nginx/html/*
        cp -R /lzcapp/pkg/content/. /usr/share/nginx/html/
      fi
locales:
  en:
    name: TaoYuan
    description: (LazyCat Auto-build) Chinese pastoral life sim game that runs without a backend
  zh:
    name: 桃源乡
    description: （懒猫微服自动构建）纯前端运行的中文田园模拟经营游戏
