lzc-sdk-version: '0.1'
package: fun.selfstudio.app.migration.multica
version: '0.1.14'
min_os_version: 1.3.8
name: multica
description: multica on LazyCat
license: Apache-2.0
homepage: https://multica.ai
author: multica-ai
application:
  subdomain: multica
  public_path:
    - /
  upstreams:
    -
      location: /
      backend: http://postgres:5432/
services:
  postgres:
    image: registry.lazycat.cloud/invokerlaw/codeeagle/multica:33743fa32ef3d724
    environment:
      - POSTGRES_DB=multica
      - POSTGRES_USER=multica
      - POSTGRES_PASSWORD=multica
    binds:
      - /lzcapp/var/db/multica/postgres:/var/lib/postgresql/data
locales:
  en:
    name: multica
    description: multica on LazyCat
  zh:
    name: multica
    description: （迁移初稿）Multica 的懒猫微服版本
