application:
  public_path:
    - /
  subdomain: dvc
  upstreams:
    -
      backend: http://git-server:2222/
      location: /
author: treeverse
description: Data Versioning and ML Experiments
homepage: https://dvc.org
license: Apache-2.0
locales:
  en:
    description: Data Versioning and ML Experiments
    name: dvc
  zh:
    description: （迁移初稿）Dvc 的懒猫微服版本
    name: dvc
lzc-sdk-version: '0.1'
min_os_version: 1.3.8
name: dvc
package: fun.selfstudio.app.migration.dvc
services:
  git-server:
    binds:
      - /lzcapp/var/data/dvc/git-server/key:/tmp/key
      - /lzcapp/var/data/dvc/git-server/custom-cont-init-d:/custom-cont-init.d
    environment:
      - USER_NAME=user
      - PUBLIC_KEY_FILE=/tmp/key
    image: registry.lazycat.cloud/placeholder/dvc:git-server
version: 3.67.1
