lzc-sdk-version: '0.1'
package: fun.selfstudio.app.migration.hermes-webui
version: 0.38.6
min_os_version: 1.3.8
name: hermes-webui
description: Hermes WebUI
license: MIT
homepage: https://github.com/nesquena/hermes-webui
author: nesquena
application:
  subdomain: hermes-webui
  public_path:
    - /
  upstreams:
    -
      location: /
      backend: http://hermes-webui:8787/
services:
  hermes-webui:
    image: registry.lazycat.cloud/placeholder/hermes-webui:hermes-webui
    environment:
      - HERMES_WEBUI_HOST=0.0.0.0
      - HERMES_WEBUI_PORT=8787
      - HERMES_WEBUI_STATE_DIR=/data
      - HERMES_WEBUI_AGENT_DIR=/srv/hermes-agent
      - HERMES_HOME=/srv/hermes-agent
    binds:
      - /lzcapp/var/data/hermes-webui/hermes-webui:/data
      - /lzcapp/pkg/content/hermes-agent-config:/srv/hermes-agent:ro
  hermes-agent:
    image: registry.lazycat.cloud/placeholder/hermes-agent:hermes-agent
    command: gateway run --replace
    environment:
      - HERMES_HOME=/data/.hermes
    setup_script: sh -lc 'mkdir -p /lzcapp/var/data/hermes-webui/hermes-agent-config && if [ ! -d /lzcapp/var/data/hermes-webui/hermes-agent-config/.hermes ]; then cp -r /lzcapp/pkg/content/hermes-agent-config/. /lzcapp/var/data/hermes-webui/hermes-agent-config/; fi'
    binds:
      - /lzcapp/var/data/hermes-webui/hermes-agent-config:/data/.hermes
locales:
  en:
    name: hermes-webui
    description: Hermes WebUI
  zh:
    name: hermes-webui
    description: （迁移初稿）Hermes Webui 的懒猫微服版本
