lzc-sdk-version: '0.1'
package: fun.selfstudio.app.migration.cmms
version: 1.5.0
min_os_version: 1.3.8
name: cmms
description: "#1 Self hosted CMMS web & mobile application that allows you to manage enterprise maintenance for free - Computerized Maintenance Management System"
license: AGPL-3.0
homepage: https://atlas-cmms.com
author: Grashjs
application:
  subdomain: cmms
  public_path:
    - /
  upstreams:
    -
      location: /api/
      backend: http://api:8080/
    -
      location: /minio/
      backend: http://minio:9000/
    -
      location: /
      backend: http://frontend:3000/
services:
  postgres:
    image: registry.lazycat.cloud/invokerlaw/library/postgres:c7066f661fdb4a89
    environment:
      - POSTGRES_DB=atlas
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    binds:
      - /lzcapp/var/db/cmms/postgres:/var/lib/postgresql/data
  api:
    image: registry.lazycat.cloud/invokerlaw/codeeagle/cmms-api:bb53bbcabe9ff18e
    depends_on:
      - postgres
      - minio
    environment:
      - DB_URL=postgres/atlas
      - DB_USER=${POSTGRES_USER}
      - DB_PWD=${POSTGRES_PWD}
      - PUBLIC_API_URL=https://cmms.${LAZYCAT_BOX_DOMAIN}/api
      - PUBLIC_FRONT_URL
      - GCP_BUCKET_NAME
      - GCP_JSON
      - GCP_PROJECT_ID
      - MAIL_RECIPIENTS
      - SMTP_PWD
      - SMTP_USER
      - SMTP_HOST
      - SMTP_PORT
      - SPRING_PROFILES_ACTIVE
      - JWT_SECRET_KEY
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_BUCKET=atlas-bucket
      - MINIO_ACCESS_KEY=${MINIO_USER}
      - MINIO_SECRET_KEY=${MINIO_PASSWORD}
      - STORAGE_TYPE=${STORAGE_TYPE:-minio}
      - PUBLIC_MINIO_ENDPOINT=https://cmms.${LAZYCAT_BOX_DOMAIN}/minio
      - INVITATION_VIA_EMAIL=${INVITATION_VIA_EMAIL:-false}
      - ENABLE_EMAIL_NOTIFICATIONS=${ENABLE_EMAIL_NOTIFICATIONS:-false}
      - ENABLE_SSO=${ENABLE_SSO:-false}
      - OAUTH2_PROVIDER
      - OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET
      - LICENSE_KEY=${LICENSE_KEY:-}
      - LICENSE_FINGERPRINT_REQUIRED=${LICENSE_FINGERPRINT_REQUIRED:-true}
      - LICENSE_FILE_PATH=${LICENSE_FILE_PATH:-}
      - ALLOWED_ORGANIZATION_ADMINS=${ALLOWED_ORGANIZATION_ADMINS:-}
      - LOGO_PATHS
      - CUSTOM_COLORS
      - BRAND_CONFIG
      - PADDLE_API_KEY=${PADDLE_API_KEY:-}
      - PADDLE_WEBHOOK_SECRET_KEY=${PADDLE_WEBHOOK_SECRET_KEY:-}
      - PADDLE_ENVIRONMENT=${PADDLE_ENVIRONMENT:-sandbox}
      - ENABLE_CORS=${ENABLE_CORS:-true}
      - KEYGEN_PRODUCT_TOKEN=${KEYGEN_PRODUCT_TOKEN:-}
      - MAIL_TYPE=${MAIL_TYPE:-smtp}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL:-}
      - SENDGRID_CONTACT_LIST_ID=${SENDGRID_CONTACT_LIST_ID:-}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY:-}
    binds:
      - /lzcapp/var/data/cmms/api/images:/app/static/images
      - /lzcapp/var/data/cmms/api/config:/app/static/config
  frontend:
    image: registry.lazycat.cloud/invokerlaw/codeeagle/cmms-frontend:50f231e20c7defa8
    depends_on:
      - api
    environment:
      - API_URL=https://cmms.${LAZYCAT_BOX_DOMAIN}/api
      - GOOGLE_KEY=${GOOGLE_KEY:-}
      - GOOGLE_TRACKING_ID=${GOOGLE_TRACKING_ID:-}
      - INVITATION_VIA_EMAIL=${INVITATION_VIA_EMAIL:-false}
      - CLOUD_VERSION=${CLOUD_VERSION:-false}
      - NODE_ENV=production
      - ENABLE_SSO=${ENABLE_SSO:-false}
      - OAUTH2_PROVIDER=${OAUTH2_PROVIDER:-}
      - LOGO_PATHS=${LOGO_PATHS:-}
      - CUSTOM_COLORS=${CUSTOM_COLORS:-}
      - BRAND_CONFIG=${BRAND_CONFIG:-}
      - DEMO_LINK=${DEMO_LINK:-}
      - PADDLE_SECRET_TOKEN=${PADDLE_SECRET_TOKEN:-}
      - PADDLE_ENVIRONMENT=${PADDLE_ENVIRONMENT:-sandbox}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY:-}
  minio:
    image: registry.lazycat.cloud/invokerlaw/minio/minio:04662dc938f19824
    command: server --address ":9000" --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    binds:
      - /lzcapp/var/data/cmms/minio:/data
locales:
  en:
    name: cmms
    description: "#1 Self hosted CMMS web & mobile application that allows you to manage enterprise maintenance for free - Computerized Maintenance Management System"
  zh:
    name: cmms
    description: （迁移初稿）Cmms 的懒猫微服版本
